# Generated by Django 4.1.2 on 2022-10-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cdate',
            field=models.DateField(),
        ),
    ]
